add apply patch issue and update baseline hash search

diff --git a/.github/workflows/run_checks.yaml b/.github/workflows/run_checks.yaml
--- a/.github/workflows/run_checks.yaml
+++ b/.github/workflows/run_checks.yaml
@@ -112,9 +112,23 @@ jobs:
           git fetch
           git checkout ${{ inputs.gcchash }}
 
+      - name: Create pending issue
+        run: |
+          echo "# Apply Patch Status ${{ inputs.patch_name }}" > issue.md
+          echo "\nPending\n" >> issue.md
+
+      - name: Create apply report issue
+        uses: JasonEtco/create-an-issue@v2
+        id: create-issue
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          filename: issue.md
+          update_existing: true
+
       - name: Report that we're now attempting to apply the patch
         run: |
-          python scripts/post_check_to_patchworks.py -pid $(tail -n 1 patches/${{ inputs.patch_name }}) -desc 'Attempting to apply patch to tip-of-tree' -rid ${{ github.run_id }} -state 'pending' -context 'apply-patch'
+          python scripts/post_check_to_patchworks.py -pid $(tail -n 1 patches/${{ inputs.patch_name }}) -desc 'Attempting to apply patch to tip-of-tree' -iid ${{ steps.update-issue.outputs.number }} -state 'pending' -context 'apply-patch'
         continue-on-error: true
 
       - name: Apply patches to baseline
@@ -123,10 +137,11 @@ jobs:
           cd gcc
           git config user.name "GitHub Actions Bot"
           git config user.email "<>"
-          git am ../patches/*.patch --whitespace=fix -q &> out || true
+          git am ../patches/*.patch --whitespace=fix -q --3way &> out || true
           cat out
           if [[ $(cat out | wc -l) != 0 ]]; then
             echo "Failed to apply patch cleanly to baseline hash"
+            git am --show-current-patch=diff &>> out
             git am --abort
             echo "apply_baseline=false" >> $GITHUB_OUTPUT
             rm out
@@ -142,10 +157,11 @@ jobs:
           git reset --hard origin/master
           git pull origin master
           export TOT_HASH=$(git rev-parse HEAD)
-          git am ../patches/*.patch --whitespace=fix -q &> out || true
+          git am ../patches/*.patch --whitespace=fix -q --3way &> out || true
           cat out
           if [[ $(cat out | wc -l) != 0 ]]; then
             echo "Failed to apply patch cleanly to tip of tree"
+            git am --show-current-patch=diff &>> out
             git am --abort
             echo "apply_tot=false" >> $GITHUB_OUTPUT
             rm out
@@ -155,11 +171,6 @@ jobs:
           echo "tot_hash=$TOT_HASH" >> $GITHUB_OUTPUT
         continue-on-error: true
 
-      - name: Report patch failed to apply to tip of tree
-        if: ${{ steps.apply-baseline.outputs.apply_baseline == 'true' && steps.apply-tip-of-tree.outputs.apply_tot == 'false' }}
-        run: |
-          python scripts/post_check_to_patchworks.py -pid $(tail -n 1 patches/${{ inputs.patch_name }}) -desc 'Patch did not apply to tip of tree.' -rid ${{ github.run_id }} -state 'warning' -context 'apply-patch'
-        continue-on-error: true
 
       - name: Check build only
         id: build-only
@@ -173,10 +184,38 @@ jobs:
         run: |
           echo "early_exit=true" >> $GITHUB_OUTPUT
 
+      - name: Build early exit report
+        if: ${{ steps.early-exit.outputs.early_exit == 'true' }}
+        run: |
+          echo "# Apply Patch Status ${{ inputs.patch_name }}" > issue.md
+          echo "\nFailed to apply patch\n" >> issue.md
+          cat out >> issue.md
+
+      - name: Build success report
+        if: ${{ steps.apply-tip-of-tree.outputs.apply_tot == 'true' }}
+        run: |
+          echo "# Apply Patch Status ${{ inputs.patch_name }}" > issue.md
+          echo "\nSuccess\n" >> issue.md
+
+      - name: Update apply issue
+        uses: JasonEtco/create-an-issue@v2
+        id: update-issue
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          filename: issue.md
+          update_existing: true
+
+      - name: Report patch failed to apply to tip of tree
+        if: ${{ steps.apply-baseline.outputs.apply_baseline == 'true' && steps.apply-tip-of-tree.outputs.apply_tot == 'false' }}
+        run: |
+          python scripts/post_check_to_patchworks.py -pid $(tail -n 1 patches/${{ inputs.patch_name }}) -desc 'Patch did not apply to tip of tree.' -iid ${{ steps.update-issue.outputs.number }} -state 'warning' -context 'apply-patch'
+        continue-on-error: true
+
       - name: Report patch applied to tip of tree successfully
         if: ${{ steps.apply-tip-of-tree.outputs.apply_tot == 'true' }}
         run: |
-          python scripts/post_check_to_patchworks.py -pid $(tail -n 1 patches/${{ inputs.patch_name }}) -desc 'Patch applied to tip of tree successfully.' -rid ${{ github.run_id }} -state 'success' -context 'apply-patch'
+          python scripts/post_check_to_patchworks.py -pid $(tail -n 1 patches/${{ inputs.patch_name }}) -desc 'Patch applied to tip of tree successfully.' -iid ${{ steps.update-issue.outputs.number }} -state 'success' -context 'apply-patch'
         continue-on-error: true
 
       - name: Output new gcchash
@@ -188,7 +227,7 @@ jobs:
           if [ "${{ steps.apply-baseline.outputs.apply_baseline }}" == "true" ]; then
             git checkout ${{ inputs.gcchash }}
           fi
-          git am ../patches/*.patch --whitespace=fix
+          git am ../patches/*.patch --whitespace=fix --3way
           export NEW_GCCHASH=$(git rev-parse HEAD)
           echo $NEW_GCCHASH
           echo "new_gcchash=$NEW_GCCHASH" >> $GITHUB_OUTPUT
